### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by emcaulay**
I edited the section about the expanded curricula. I think I understand correctly what the paragraph is trying to say. But I'm not sure. 

My understanding is that you can elect to have a standard Library Carpentry workshop (as opposed to a Library Carpentry-based workshop] you must choose one of the four curricula from the table.

I think my confusion is around the use of the word "standard" to describe a workshop and also as a keyword in the title of one of the options for the curriculum. 

Apologies if my edits are too fussy.

### CODE REVIEW

**Comment by libcce** [comment]
@emcaulay "standard" workshop may be the preferred term used by The Carpentries still? @maneesha can you confirm?

**Comment by maneesha** [comment]
I think @sheraaronhurt  can best advise on this.  Sher, are we using "standard" to refer to these workshops?

**Comment by emcaulay** [comment]
To clarify, I think my confusion is around this sentence:

"The table below includes two new curricula beyond the standard workshop." 

I think there are two things that confuse me. The use of the word 'beyond' makes me think that these are "more advanced" workshops, which I don't think is the intended meaning. And then the table has four rows, which means there are 3 additional curricula beyond the first row which is the "Library Carpentry Standard Workshop."

Maybe a revision could be:

"The table below display four possible curricula that can serve as a Library Carpentry workshop. They include the original "Library Carpentry Standard Workshop" as well as three other options that are equally supported."

My concern remains that I may not fully be understanding the nuance of the language and therefore I might be missing the intention of this paragraph and table. 

And I do apologize if this is just too nit picky!

**Comment by libcce** [comment]
@emcaulay don't apologize! Your suggestion looks good to me and I think it will help! @ppival @sharilaster what do you think?

**Comment by sharilaster** [comment]
Hey y'all! @emcaulay I agree that you've identified a point where the current wording is not clear, and your suggested approach in this thread makes sense. @libcce @ppival Where I'm not quite following is the "Custom" option -- is this considered a fourth standard curriculum, or is this more of an invitation to consider options beyond the three standard curricula listed?

(And apologies to all, I somehow missed that I am the lead maintainer for this lesson?! I will do better responding to issues and PRs in the future.)

**Comment by libcce** [comment]
@sharilaster I think at this point it is more like an invitation to consider these options beyond the standard curriculum. So maybe @emcaulay suggestion still needs some tweaking? So this part "as well as three other options that are equally supported." to something like "as well as three other options to consider."

**Comment by sharilaster** [comment]
@libcce I do like the "equally supported" wording, because it more strongly presents the idea that the alternatives are also valid curricula. Would it work to take the last row off the table and instead describe it as another approach to creating a workshop? Or, if that is less clear, how about this? "The table below includes the standard workshop curriculum, two additional curricula that are equally supported, and a custom option."

**Comment by libcce** [comment]
Works for me @sharilaster!

**Comment by ppival** [comment]
I like it too, @sharilaster and @libcce

**Comment by emcaulay** [comment]
Thanks for the discussion, everyone! Very fun and helpful for me in becoming more involved. 

The only question I have remaining is if the custom workshop, the fourth row, should be highlighted in the table at all. Maybe we want to keep that in prose or distinguish it from the other three curricula? 

My thinking is: The Library Carpentry organization has agreed that there are 3 established curricula that qualify as Library Carpentry workshops. The custom option would need custom approval I think and not quite the same thing?

**Comment by sheraaronhurt** [comment]
Thanks for the discussion! The Core Team defines "standard" as any 3 of the 4 curricula being taught. Anything different would be considered a Mix and Match on our end :)

**Comment by sharilaster** [comment]
@emcaulay my understanding is that instructors do not need approval to teach a custom workshop, and the custom option allows flexibility for tailoring the workshop to anticipated learners' needs. @libcce do I have this right?

In terms of resolving #26, it looks like everyone is okay with my suggested modification? If so... @emcaulay if you would like to update on your side, we can go that way, or if you prefer handing it off I will look up how to do it on our side.  Either way. :-)

**Comment by libcce** [comment]
@sharilaster your language worked for me. We have to update "custom" to "Mix and Match" to align with how The Carpentries refers to them. Otherwise, looks good to me! Thanks @emcaulay!

**Comment by emcaulay** [comment]
I think I have captured the meaning of our conversation in the edits I have proposed. However, it might not be quite right yet. Please review again, especially @libcce and @sharilaster. Thank you all !

**Comment by emcaulay** [comment]
Here's an additional / related discussion point. The paragraph after the table is about the Core Lessons and doesn't seem in line with the greater flexibility introduced in the Curricula section. 

It says:

> Core Lessons
> For a standard Library Carpentry workshop, three of the four parts below must be taught in addition to having at least one certified Carpentries instructor teach the workshop. Alternatively, a Library Carpentry-based workshop can be considered, where part(s) of the core lessons are combined with the extended lessons to suit the needs of the community.

I think the section on Curricula makes me think that there are 3 curricula that are all equally verified as being Library Carpentry workshops (as opposed to being alternatives that are under the Library Carpentry-based umbrella). 

If that is true, then it's possible that the Core Lessons section is no longer valid?

**Comment by libcce** [comment]
@emcaulay I prefer the former and not the latter. But I also think we might want to ask you @emcaulay and others on this thread to attend the next LC Advisory Group meeting because if these questions are coming up (and big thank you @emcaulay for bring this up) we really need to settle on the right language. @ragamouf @arieldeardorff can we add this item to our next agenda and invite @emcaulay @sharilaster et al?

**Comment by emcaulay** [comment]
I would be happy to attend a meeting, depending on if the LC Advisory Group is interested. 

Meanwhile, I'll keep reading and getting better informed about the Library Carpentry. I'm prepping to teach for the first time in 2 weeks, so I'm re-reading everything carefully.

**Comment by arieldeardorff** [comment]
Thanks @libcce! As an alternative, maybe this is something we could bring up in the LC Curriculum sub-committee that @ragamouf chairs? That might help get this figured out sooner than if we wait for the Sept LC Advisory meeting. Thoughts @ragamouf?

**Comment by emcaulay** [comment]
I think the LC Curriculum subcommittee should review. Here's another piece of data that contributes to uncertainty: I also opened up the "Request a Workshop" form (https://amy.carpentries.org/forms/request_workshop/) and there is only one option offered for Library Carpentry. It is: "Library Carpentry (Intro to Data, Unix Shell, Git, and/or OpenRefine)". 

Therefore, the option to request any of the four curricula listed in the table on the lc-overview page is not supported by the form. So, it seems like part of the documentation is in support of a variety of curricula while the actual request form is not.

**Comment by sharilaster** [comment]
Ok! @libcce @ppival  I propose merging #26 as updated and then opening a new issue to facilitate discussion and clarification on what constitutes LC curriculum, capturing points that @emcaulay @arieldeardorff @libcce made here. Does that work, or should we wait on this until the group has had broader discussion?

**Comment by libcce** [comment]
@sharilaster sounds good! @ppival if you agree, can you merge? 

@arieldeardorff @ragamouf it would be great if we could put this on the LC Advisory Group agenda as an item -> How we communicate LC curricula and point to this PR thread? If possible, would be great to invite @emcaulay to walk us through her observations? If we aren't clear about the LC offerings then this is an opportunity to improve.

**Comment by emcaulay** [comment]
I have entered an issue (#30), please feel free to add to the issue and make it more useful.

**Comment by emcaulay** [comment]
@ppival , per discussion above, I think this leaves this particular PR for your review and decision. Thanks!

**Comment by ppival** [comment]
Thanks all!

**Pull request merged**
